version: '3'
services:
	zabbix_server:
		image: zabbix/zabbix-server-mysql:centos-3.4-latest
		restart: always
		environment:
			DB_SERVER_HOST: zabbix_db
			DB_SERVER_PORT: 3306
			MYSQL_USER: zabbix
			MYSQL_PASSWORD: zabbix
			MYSQL_DATABASE: zabbix
		ports:
			- "10050:10050"
			- "10051:10051"
		networks:
			- zabbix_network
		depends_on:
			- zabbix_db
	
	zabbix_frontend:
		image: zabbix/zabbix-web-nginx-mysql:centos-3.4-latest
		restart: always
		environment:
			ZBX_SERVER_HOST: zabbix_server
			ZBX_SERVER_PORT: 10051
			DB_SERVER_HOST: zabbix_db
			DB_SERVER_PORT: 3306
			MYSQL_USER: zabbix
			MYSQL_PASSWORD: zabbix
			MYSQL_DATABASE: zabbix
			PHP_TZ: "America/Sao_Paulo"
			ZBX_SERVER_NAME: Zabbix-Azure-Docker
		ports:
			- "80:80"
		networks:
			- zabbix_network
		depends_on:
			- zabbix_db
			- zabbix_server
	
	zabbix_db:
		image: mysql:5.7
		restart: always
		environment:
			MYSQL_ROOT_PASSWORD: root
			MYSQL_USER: zabbix
			MYSQL_PASSWORD: zabbix
			MYSQL_DATABASE:	zabbix
		volumes:
			- zabbix_db:/var/lib/mysql		
		ports:
			- "3306:3306"
		networks:
			- zabbix_network


networks:
	zabbix_network:

volumes:
	zabbix_db:
